### ISSUE TITLE
Error loading mods: blueprint_plip_and_turn(100.8.4)

### ISSUE THREAD

**Issue by dennyh** [tst2005factorio/blueprint_flip_and_turn#4]
Just updated the mod today and now it wont load:
`Failed to load mods: The given sprite rectangle (left_top=72x0,right_bottom=108x36) it outside the actual sprite size (left_top=0x0,right_bottom=72x72).: __blueprint_flip_and_turn__/graphics/gui.png`

**Comment by briang** [comment]
[Further discussion](https://mods.factorio.com/mod/blueprint_flip_and_turn/discussion/5fa15cbe3bc8d54551be676b)

**Comment by tst2005** [comment]
Thanks for your feedback.
It should be fixed in 100.8.5.

**Comment by MadTony33** [comment]
Thanks for the quick action. Great mod.

Tony
